package com.example.healthy.vm

import androidx.lifecycle.ViewModel

class ConsultationViewModel : ViewModel() {

     fun getSymptoms() = listOf(
        "Fever",
        "Cough",
        "Shortness of breath",
        "Fatigue",
        "Sore throat",
        "Runny nose",
        "Sneezing",
        "Headache",
        "Muscle pain",
        "Joint pain",
        "Chest pain",
        "Abdominal pain",
        "Nausea",
        "Vomiting",
        "Diarrhea",
        "Constipation",
        "Loss of appetite",
        "Unintentional weight loss",
        "Dizziness",
        "Fainting",
        "Confusion",
        "Memory loss",
        "Difficulty concentrating",
        "Blurred vision",
        "Double vision",
        "Eye redness",
        "Eye pain",
        "Hearing loss",
        "Ear pain",
        "Ringing in ears (Tinnitus)",
        "Nasal congestion",
        "Nosebleeds",
        "Sinus pressure",
        "Difficulty swallowing",
        "Hoarseness",
        "Swollen lymph nodes",
        "Skin rash",
        "Itchy skin",
        "Hives",
        "Dry skin",
        "Excessive sweating",
        "Night sweats",
        "Chills",
        "Tremors",
        "Numbness",
        "Tingling",
        "Burning sensation",
        "Weakness",
        "Palpitations",
        "High blood pressure",
        "Low blood pressure",
        "Frequent urination",
        "Painful urination",
        "Blood in urine",
        "Incontinence",
        "Decreased urine output",
        "Erectile dysfunction",
        "Irregular menstrual cycle",
        "Heavy menstrual bleeding",
        "Missed periods",
        "Painful periods",
        "Breast tenderness",
        "Lump in breast",
        "Swelling in legs",
        "Swelling in arms",
        "Difficulty breathing",
        "Wheezing",
        "Persistent hiccups",
        "Chronic cough",
        "Coughing up blood",
        "Loss of smell",
        "Loss of taste",
        "Bad breath",
        "Mouth ulcers",
        "Swollen tongue",
        "White patches in mouth",
        "Sore gums",
        "Tooth pain",
        "Jaw pain",
        "Neck stiffness",
        "Back pain",
        "Hip pain",
        "Knee pain",
        "Ankle pain",
        "Foot pain",
        "Hand pain",
        "Wrist pain",
        "Shoulder pain",
        "Difficulty moving",
        "Unsteady gait",
        "Seizures",
        "Hallucinations",
        "Mood swings",
        "Depression",
        "Anxiety",
        "Panic attacks",
        "Paranoia",
        "Agitation",
        "Insomnia",
        "Excessive sleepiness",
        "Nightmares",
        "Bruising easily",
        "Slow wound healing",
        "Yellow skin (Jaundice)",
        "Pale skin",
        "Dark urine"
    )
}